package com.educationcrm.dialer.models

object DialerErrorCodes {
    const val PERMISSION_DENIED = "PERMISSION_DENIED"
    const val NOT_DEFAULT_DIALER = "NOT_DEFAULT_DIALER"
    const val INVALID_PHONE_NUMBER = "INVALID_PHONE_NUMBER"
    const val CONNECTION_FAILED = "CONNECTION_FAILED"
    const val RECORDING_INIT_FAILED = "RECORDING_INIT_FAILED"
    const val RECORDING_STOPPED_UNEXPECTEDLY = "RECORDING_STOPPED_UNEXPECTEDLY"
    const val LOW_STORAGE = "LOW_STORAGE"
    const val UPLOAD_FAILED = "UPLOAD_FAILED"
}
